# Generated by Django 3.0.5 on 2020-04-17 09:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='geometria_web',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='geometria_web',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857),
        ),
    ]
