# Generated by Django 3.0.5 on 2020-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='fecha_actualizacion',
            field=models.DateField(help_text='La base de datos se alimenta diariamente, esta variable permite identificar la fecha de la ultima actualizacion.', null=True),
        ),
    ]
