# Generated by Django 3.0.5 on 2020-04-17 16:34

import covid_update.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covid_data', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo', models.FilePathField(path=covid_update.models.obtener_directorio_casos, unique=True)),
                ('log', models.FilePathField(null=True, path=covid_update.models.obtener_directorio_logs)),
            ],
        ),
    ]
