# Generated by Django 3.0.5 on 2020-04-14 07:30
import os

from django.db import migrations
from django.contrib.gis.utils import LayerMapping


RUTA_ENTIDADES_SHP = os.path.join(
    os.path.dirname(os.path.dirname(__file__)),
    'data',
    'marco_geoestadistico',
    'ent',
    '01_32_ent.shp')

MAPEO_CAMPOS = {
    'clave': 'CVE_ENT',
    'nombre': 'NOMGEO',
    'geometria': 'POLYGON'
}


def cargar_entidades(apps, schema_editor):
    Entidad = apps.get_model("covid_data", "Entidad")
    lm = LayerMapping(
        Entidad,
        RUTA_ENTIDADES_SHP,
        MAPEO_CAMPOS,
        transform=False)
    lm.save(strict=True, verbose=True)


class Migration(migrations.Migration):
    dependencies = [
        ('covid_data', '0001_initial')
    ]

    operations = [
        migrations.RunPython(cargar_entidades)
    ]
