# Generated by Django 3.0.5 on 2020-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covid_update', '0003_paises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actualizacion', models.DateField(auto_now_add=True)),
                ('archivo', models.FilePathField(path='/Users/erobredo/Documents/otros/covid/django_covid/datos/casos/')),
                ('log', models.FilePathField(null=True, path='/Users/erobredo/Documents/otros/covid/django_covid/datos/logs/')),
            ],
        ),
    ]
