# Generated by Django 3.0.5 on 2020-04-14 07:31
import os
import pandas as pd
from django.db import transaction
from django.db import migrations


RUTA_PAISES = os.path.join(
    os.path.dirname(os.path.dirname(__file__)),
    'data',
    'paises.csv')


@transaction.atomic
def cargar_paises(apps, schema_editor):
    """Datos de paises obtenidos del banco mundial.
    """
    Pais = apps.get_model("covid_data", "Pais")
    paises = pd.read_csv(RUTA_PAISES, index_col=0, encoding='latin-1')

    for _, pais in paises.iterrows():
        descripcion = pais['Economy']
        codigo = pais['Code']
        region = pais['Region']

        pais, creado = Pais.objects.get_or_create(
            clave=codigo,
            descripcion=descripcion,
            codigo=codigo,
            region=region)

        if creado:
            print(f'Pais creado {pais}')


class Migration(migrations.Migration):

    dependencies = [
        ('covid_update', '0003_municipios'),
    ]

    operations = [
        migrations.RunPython(cargar_paises)
    ]
